Better error message when command does not exist
Check the command argument to make sure it exists before passing it to other commands.

diff --git a/script/ev3dev-mocks-run.in b/script/ev3dev-mocks-run.in
--- a/script/ev3dev-mocks-run.in
+++ b/script/ev3dev-mocks-run.in
@@ -9,6 +9,11 @@ if [ $# -eq 0 ]; then
 fi
 
 command=$(which "$1")
+if [ "$command" == "" ]; then
+    echo "Could not find \"$1\" in \$PATH"
+    exit 1
+fi
+
 magic=$(od -N 4 -t x1 -A n "$command")
 if [ "$magic" != " 7f 45 4c 46" ]; then
     echo "<command> must be ELF binary"
